import type { FilePatchPlan } from "../patcher/index.js";
import type { ChangeEvent } from "../types.js";
import type { ValidationStepResult } from "../validator/index.js";

export interface PrContent {
  title: string;
  body: string;
  branchName: string;
  commitMessage: string;
}

export interface PrTemplateInput {
  provider: string;
  fromVersion: string;
  toVersion: string;
  events: ChangeEvent[];
  plans: FilePatchPlan[];
  validation?: ValidationStepResult[];
}

export function generatePrContent(input: PrTemplateInput): PrContent {
  const fromShort = shortVersion(input.fromVersion);
  const toShort = shortVersion(input.toVersion);

  const title = `${input.provider}: update for ${fromShort} → ${toShort}`;

  const branchName = `driftpatch/${input.provider}/${fromShort}-${toShort}-${Date.now().toString(36).slice(-4)}`;

  const commitMessage = [
    title,
    "",
    `Updates ${input.provider} integration for ${input.events.length} upstream change(s).`,
    "",
    "Generated by DriftPatch.",
  ].join("\n");

  const body = renderBody(input, fromShort, toShort);

  return { title, body, branchName, commitMessage };
}

function renderBody(input: PrTemplateInput, fromShort: string, toShort: string): string {
  const lines: string[] = [];

  lines.push(`## Summary`);
  lines.push("");
  lines.push(
    `This PR updates the **${input.provider}** integration in response to upstream changes between \`${fromShort}\` and \`${toShort}\`.`,
  );
  lines.push("");
  lines.push("Generated automatically by DriftPatch from the upstream diff and the local repo skill.");
  lines.push("");

  lines.push(`## Upstream changes detected (${input.events.length})`);
  lines.push("");
  for (const event of input.events) {
    const tag = `[${event.kind} · risk:${event.risk}]`;
    lines.push(`- ${tag} \`${event.entity}\` — ${event.description}`);
  }
  lines.push("");

  const patchedPlans = input.plans.filter((p) => p.status === "patch");
  const skippedPlans = input.plans.filter((p) => p.status === "skip");
  const reviewPlans = input.plans.filter((p) => p.status === "manual_review");

  lines.push(`## Files changed (${patchedPlans.length})`);
  lines.push("");
  if (patchedPlans.length === 0) {
    lines.push("(no files modified)");
  } else {
    for (const plan of patchedPlans) {
      const blockSummary = plan.blocks.length === 1 ? "1 block" : `${plan.blocks.length} blocks`;
      lines.push(`- \`${plan.filePath}\` — ${blockSummary}`);
      if (plan.notes && plan.notes.trim().length > 0) {
        lines.push(`  - ${plan.notes.trim().split("\n")[0]}`);
      }
    }
  }
  lines.push("");

  if (reviewPlans.length > 0) {
    lines.push(`## Files flagged for manual review (${reviewPlans.length})`);
    lines.push("");
    for (const plan of reviewPlans) {
      lines.push(`- \`${plan.filePath}\` — ${plan.notes.trim().split("\n")[0] ?? "needs human judgment"}`);
    }
    lines.push("");
  }

  if (skippedPlans.length > 0) {
    lines.push(`<details>`);
    lines.push(`<summary>Files considered but not modified (${skippedPlans.length})</summary>`);
    lines.push("");
    for (const plan of skippedPlans) {
      lines.push(`- \`${plan.filePath}\` — ${plan.notes.trim().split("\n")[0] ?? "no change required"}`);
    }
    lines.push("");
    lines.push(`</details>`);
    lines.push("");
  }

  if (input.validation && input.validation.length > 0) {
    lines.push(`## Validation`);
    lines.push("");
    for (const step of input.validation) {
      const symbol = step.passed ? "✓" : "✗";
      lines.push(`- ${symbol} \`${step.command}\` (${step.durationMs}ms)`);
    }
    lines.push("");
  }

  lines.push(`## What you should verify`);
  lines.push("");
  lines.push(`- Confirm the new attributes/methods/parameters introduced in this version are correctly exposed through your wrapper(s).`);
  lines.push(`- Run your full validation suite (the skill ran a subset).`);
  lines.push(`- Spot-check the modified files for fit with your project's conventions.`);
  lines.push("");
  lines.push(`---`);
  lines.push(`🤖 Generated by [DriftPatch](https://github.com/anthropics/claude-code) · upstream changes pulled deterministically, patches drafted by Claude.`);

  return lines.join("\n");
}

function shortVersion(version: string): string {
  if (/^[a-f0-9]{40}$/i.test(version)) return version.slice(0, 8);
  if (version === "current") return "current";
  return version;
}
